name: Cucumber API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  run-cucumber-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Run Cucumber API tests
        run: mvn test -Dtest=runners.TestRunner # Adjust package if needed

      - name: Archive test reports
        if: always() # Save reports even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-api-test-reports
          path: newCucumberAPIProject/target/cucumber-reports # Adjust based on your config

      - name: Notify on failure
        if: failure()
        run: echo "Cucumber API Tests Failed!" # Replace with Slack/Email integration if needed
